In [1]:
import pandas as pd

In [2]:
df1 = pd.read_json("../Data/code_alpaca_20k.json")
df1

,instruction,input,output
0,Create an array of length 5 which contains all...,,"arr = [2, 4, 6, 8, 10]"
1,Formulate an equation to calculate the height ...,,Height of triangle = opposite side length * si...
2,Write a replace method for a string class whic...,"string = ""Hello World!""\nreplace_with = ""Greet...","def replace(self, replace_with):\n new_stri..."
3,Create an array of length 15 containing number...,,"arr = [3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33..."
4,Write a function to find the number of distinc...,"matrix = [[1, 0, 0],\n [1, 0, 1],\n ...",def find_num_distinct_states(matrix):\n sta...
...,...,...,...
20017,Identify and display all the data types within...,,SELECT DISTINCT data_type \nFROM products \nWH...
20018,Create a basic Python script to accept two num...,,"num1 = int(input(""Enter the first number: ""))\..."
20019,Create a basic C# program to print out the cur...,,using System;\n\npublic class Program \n{\n ...
20020,Find and display all the employees who earn mo...,,SELECT e.name \nFROM employees e \nWHERE e.sal...
20021,Create a Python program to accept a string fro...,Hello World,def countVowels(str): \n\tvowel = 0\n\tfor i i...

In [3]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20022 entries, 0 to 20021
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   instruction  20022 non-null  object
 1   input        20022 non-null  object
 2   output       20022 non-null  object
dtypes: object(3)
memory usage: 469.4+ KB

In [4]:
df1.isnull().sum()

instruction    0
input          0
output         0
dtype: int64

In [5]:
df2 = pd.read_csv("../Data/computer_science_synthetic_dataset.csv")
df3 = pd.read_csv("../Data/computer_science_synthetic_dataset1.csv")
df4 = pd.read_csv("../Data/computer_science_synthetic_dataset2.csv")

In [6]:
df2

,id,input,output
0,1,what are the different ways to input data into...,There are several ways to input data into a pr...
1,2,Can you please tell me about the basics of cre...,Binary search tree (BST) is a data structure t...
2,3,how do i get started in android development ?,Android development is a popular field in the ...
3,4,What should I learn next after learning about ...,You should learn about operating systems and p...
4,5,What are the basic concepts of computer progra...,Computer programming is a way of communicating...
...,...,...,...
29995,29996,"As a programmer, I\'m curious to learn more ab...","As a programmer, you are already familiar with..."
29996,29997,I want to know what are the programming concep...,You can learn a lot about programming concepts...
29997,29998,"What is the difference between ""break"" and ""co...","The ""break"" and ""continue"" statements are both..."
29998,29999,What is the difference between a class and an ...,"In computer programming, a class is a blueprin..."
29999,30000,How can I develop a simple chatbot?,A chatbot is a computer program that simulates...

In [7]:
df3

,id,input,output
0,1,what are the different ways to input data into...,There are several ways to input data into a pr...
1,2,Can you please tell me about the basics of cre...,Binary search tree (BST) is a data structure t...
2,3,how do i get started in android development ?,Android development is a popular field in the ...
3,4,What should I learn next after learning about ...,You should learn about operating systems and p...
4,5,What are the basic concepts of computer progra...,Computer programming is a way of communicating...
...,...,...,...
14994,14995,What are some good websites for learning about...,One good website for learning about operating ...
14995,14996,"As a beginner in computer science, I have a qu...","As a beginner in computer science, it is impor..."
14996,14997,Hello! I'm curious about the concept of binary...,You can learn about binary trees in computer s...
14997,14998,What are the most important concepts in Python?,"In Python, some of the most important concepts..."
14998,14999,Which computer science topics should I study n...,"In the Laguna State Polytechnic University, Ph..."

In [8]:
df4

,id,input,output
0,15000,I would like to know if I should learn about J...,"If you are a beginner, I would suggest learnin..."
1,15001,I want to learn a front end framework for web ...,"Hey there, I'm so glad you want to learn a fro..."
2,15002,How to solve problem 112 of leetcode?,I suggest that you take a look at these course...
3,15003,What are some good coding languages to learn i...,"Hello! You're at the intermediate level, so I ..."
4,15004,what is the difference between a variable and ...,A variable is a symbol that represents a value...
...,...,...,...
14996,29996,"As a programmer, I\'m curious to learn more ab...","As a programmer, you are already familiar with..."
14997,29997,I want to know what are the programming concep...,You can learn a lot about programming concepts...
14998,29998,"What is the difference between ""break"" and ""co...","The ""break"" and ""continue"" statements are both..."
14999,29999,What is the difference between a class and an ...,"In computer programming, a class is a blueprin..."
15000,30000,How can I develop a simple chatbot?,A chatbot is a computer program that simulates...

In [9]:
df2['instruction'] = ''
df3['instruction'] = ''
df4['instruction'] = ''

In [10]:
new_df2 = pd.concat([df2, df3, df4], ignore_index=True)
new_df2.drop('id',axis=1, inplace=True)

In [11]:
new_df2 = new_df2[['instruction','input', 'output']]
new_df2['instruction'] = new_df2['input']
new_df2['input'] = ''
new_df2

,instruction,input,output
0,what are the different ways to input data into...,,There are several ways to input data into a pr...
1,Can you please tell me about the basics of cre...,,Binary search tree (BST) is a data structure t...
2,how do i get started in android development ?,,Android development is a popular field in the ...
3,What should I learn next after learning about ...,,You should learn about operating systems and p...
4,What are the basic concepts of computer progra...,,Computer programming is a way of communicating...
...,...,...,...
59995,"As a programmer, I\'m curious to learn more ab...",,"As a programmer, you are already familiar with..."
59996,I want to know what are the programming concep...,,You can learn a lot about programming concepts...
59997,"What is the difference between ""break"" and ""co...",,"The ""break"" and ""continue"" statements are both..."
59998,What is the difference between a class and an ...,,"In computer programming, a class is a blueprin..."
59999,How can I develop a simple chatbot?,,A chatbot is a computer program that simulates...

In [12]:
df5 = pd.read_json("../Data/EvolInstruct-Code-80k.json")
df5

,instruction,output
0,Create a nested loop to print every combinatio...,Here is an example of a nested loop in Python ...
1,Increase the difficulty by asking to print the...,Here's the updated code to print the square of...
2,Write a function to find the number of distinc...,The given problem can be solved by iterating t...
3,Write code that removes spaces and punctuation...,Here's an example of code that attempts to sol...
4,Write a function that checks if a given number...,Here is an implementation of the function in P...
...,...,...
78259,Identify and display all the data types within...,SELECT DISTINCT data_type \nFROM products \nWH...
78260,Create a basic Python script to accept two num...,"num1 = int(input(""Enter the first number: ""))\..."
78261,Create a basic C# program to print out the cur...,using System;\n\npublic class Program \n{\n ...
78262,Find and display all the employees who earn mo...,SELECT e.name \nFROM employees e \nWHERE e.sal...
78263,Create a Python program to accept a string fro...,def countVowels(str): \n\tvowel = 0\n\tfor i i...

In [13]:
df5['input'] = ''
df5 = df5[['instruction','input', 'output']]
df5

,instruction,input,output
0,Create a nested loop to print every combinatio...,,Here is an example of a nested loop in Python ...
1,Increase the difficulty by asking to print the...,,Here's the updated code to print the square of...
2,Write a function to find the number of distinc...,,The given problem can be solved by iterating t...
3,Write code that removes spaces and punctuation...,,Here's an example of code that attempts to sol...
4,Write a function that checks if a given number...,,Here is an implementation of the function in P...
...,...,...,...
78259,Identify and display all the data types within...,,SELECT DISTINCT data_type \nFROM products \nWH...
78260,Create a basic Python script to accept two num...,,"num1 = int(input(""Enter the first number: ""))\..."
78261,Create a basic C# program to print out the cur...,,using System;\n\npublic class Program \n{\n ...
78262,Find and display all the employees who earn mo...,,SELECT e.name \nFROM employees e \nWHERE e.sal...
78263,Create a Python program to accept a string fro...,,def countVowels(str): \n\tvowel = 0\n\tfor i i...

In [14]:
df6 = pd.read_json("../Data/LeetCodeDataset-train.jsonl", lines=True)
df6 = df6[['query', 'response']]
df6['input'] = ''
df6 = df6.rename(columns={'query':'instruction', 'response': 'output'})
df6 = df6[['instruction','input', 'output']]
df6

,instruction,input,output
0,You are an expert Python programmer. You will ...,,"To solve this problem efficiently, we can use ..."
1,You are an expert Python programmer. You will ...,,```python\n# Definition for singly-linked list...
2,You are an expert Python programmer. You will ...,,```python\nclass Solution:\n def lengthOfLo...
3,You are an expert Python programmer. You will ...,,```python\nfrom typing import List\n\nclass So...
4,You are an expert Python programmer. You will ...,,```python\nclass Solution:\n def longestPal...
...,...,...,...
2636,You are an expert Python programmer. You will ...,,```python\nclass Solution:\n def simulation...
2637,You are an expert Python programmer. You will ...,,```python\nfrom typing import List\nfrom colle...
2638,You are an expert Python programmer. You will ...,,```python\nfrom typing import List\n\nclass So...
2639,You are an expert Python programmer. You will ...,,```python\nfrom typing import List\n\nclass So...
2640,You are an expert Python programmer. You will ...,,"To solve this problem, we need to simulate the..."

In [15]:
df7 = pd.read_json("../Data/sanitized-mbpp.json")
df7 = df7[['prompt', 'code']]
df7['input'] = ''
df7 = df7.rename(columns={'prompt':'instruction', 'code': 'output'})
df7 = df7[['instruction','input', 'output']]
df7

,instruction,input,output
0,Write a function to find the shared elements f...,,"def similar_elements(test_tup1, test_tup2):\n ..."
1,Write a python function to identify non-prime ...,,import math\ndef is_not_prime(n):\n result ...
2,Write a function to find the n largest integer...,,import heapq as hq\ndef heap_queue_largest(num...
3,Write a python function to check whether the t...,,def is_Power_Of_Two (x): \n return x and (n...
4,Write a function to find all words which are a...,,import re\ndef find_char_long(text):\n return...
...,...,...,...
422,Write a function that returns the list in a li...,,"def max_sum_list(lists):\n return max(lists, k..."
423,Write a function to find maximum run of upperc...,,def max_run_uppercase(test_str):\n cnt = 0\n ...
424,Write a python function to find the first odd ...,,def first_odd(nums):\n first_odd = next((el f...
425,Write a function to check if the given tuples ...,,"def check_K(test_tup, K):\n res = False\n fo..."
426,Write a function to check if each element of s...,,"def check_smaller(test_tup1, test_tup2):\n re..."

In [16]:
df_leetcode = df6
df_cs = new_df2
df_coding = pd.concat([df1, df5, df7], ignore_index=True)

In [32]:
len(df_leetcode)

2641

In [33]:
len(df_cs)

30001

In [34]:
len(df_coding)

88943

In [31]:
df_cs.drop_duplicates(inplace=True)
df_leetcode.drop_duplicates(inplace=True)
df_coding.drop_duplicates(inplace=True)

In [19]:
df_leetcode.to_json("df_leetcode.jsonl",orient="records", lines=True)
df_cs.to_json("df_cs.jsonl", orient="records", lines=True)
df_coding.to_json("df_coding.jsonl", orient="records", lines=True)